version: '3.1'
services:
  # https://hub.docker.com/_/adminer
  adminer:
    image: adminer:4.7
    restart: always
    ports:
      - 8080:8080

  # https://hub.docker.com/_/mysql
  # Use root/root as user/password credentials
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #    - dbdata:/var/lib/mysql/data
  # volumes:
  #   dbdata:
  #   # es-data:

  # es:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #      - db-data:/var/lib/mysql/data