# https://taskfile.dev
version: '2'

env:
  GOMODNAME: "github.com/cao7113/golang"
  # todo
  # TEST_DB_NAME: golang_test
  TEST_DB_URL: mysql://root:@tcp/golang_test?parseTime=true
vars:
  GREETING: Hello, Golang!
  TEST_DB_NAME: golang_test

tasks:
  hello:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:
    desc: go test
    cmds:
      - go test $GOMODNAME/trytest -v
  
  lint:
    desc: lint code
    cmds:
      - |
        PKG_LIST=$(go list $GOMODNAME/... | grep -v /vendor/)
        golint -set_exit_status ${PKG_LIST}

  ## Golangci-lint
  cilint:
    desc: run golangci-lint
    cmds:
      - golangci-lint run ./...
  cilint-try:
    desc: run golangci-lint in trytest
    cmds:
      - golangci-lint run trytest
  cilinter:
    desc: golangci-lint
    cmds:
      # https://raw.githubusercontent.com/golangci/golangci-lint/v1.20.1/.golangci.example.yml
      - golangci-lint linters -v

  run:
    cmds:
      - go run main.go

  mod:
    cmds:
      # - go mod init $GOMODNAME
      - go mod tidy -v
    
  ## docker
  dkcom-up:
    cmds:
      - docker-compose up

  ## DB
  db:
    desc: go db session
    cmds:
      - mysql -uroot {{.TEST_DB_NAME}}
  db-create:
    cmds:
      - mysql -uroot -e "create database if not exists \`{{.TEST_DB_NAME}}\`;"
  db-drop:
    cmds:
      - mysql -uroot -e "drop database if exists \`{{.TEST_DB_NAME}}\`;"
  # migrate create -ext sql -dir db/migrate create_users_table
  db-up:
    desc: migrate up
    cmds:
      - migrate -database $TEST_DB_URL -path db/migrate up
  db-down:
    desc: migrate down
    cmds:
      - migrate -database $TEST_DB_URL -path db/migrate down
  db-reset:
    cmds:
      # call tasks serially other than concurrently
      - task: db-drop
      - task: db-create
      - task: db-up
  db-dbs:
    desc: show databases
    cmds:
      - mysql -uroot -e "show databases"
  db-tables:
    desc: show tables
    cmds:
      - mysql -uroot {{.TEST_DB_NAME}} -e "show full tables"
  install-db-mig:
    desc: install migrations by https://github.com/golang-migrate/migrate/tree/master/cmd/migrate
    cmds:
      - echo should implement in Taskfile_{{GOOS}}.yml

  ## gore CLI
  cli:
    desc: Auto-importing (gore -autoimport), quit using Ctrl+D or :quit or :q
    cmds:
      - gore -autoimport
  install-gore:
    desc: install https://github.com/motemen/gore
    cmds:
      - |
        # The gore command requires Go tool-chains on runtime, so standalone binary is not distributed.
        GO111MODULE=off go get -u github.com/motemen/gore/cmd/gore
        # Make sure $GOPATH/bin is in your $PATH.
        GO111MODULE=off go get -u github.com/mdempsky/gocode   # for code completion
        GO111MODULE=off go get -u github.com/k0kubun/pp        # or github.com/davecgh/go-spew/spew