# https://taskfile.dev
version: '3'
tasks:
  gen:
    desc: gen protos protos.go file
    cmds:
      - protoc --go_out=plugins=grpc:. protos/*.proto
  run:
    desc: start grpc server
    cmds:
      - go run -v server/cmd/main.go
  try:
    desc: try it
    cmds:
      - |
        grpcurl -plaintext -proto hellopb/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
          {
          "name": "geek"
          }
        EOM
  error:
   desc: try with error
   cmds:
     - |
       grpcurl -plaintext -proto hellopb/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
         {
         "name": "geek",
         "error": "error"
         }
       EOM

  dd:
    desc: try request datadog
    cmds:
      - |
        for i in {1..1000}; do echo $i; grpcurl -plaintext -proto hello/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
          {
          "name": "geek"
          }
        EOM
        done

  dde:
    desc: try request datadog
    cmds:
      - |
        for i in {1..50}; do echo $i; grpcurl -plaintext -proto hello/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
        {
          "name": "geek",
          "error": "error"
        }
        EOM
        sleep 0.5
        done