# https://taskfile.dev
version: '3'
tasks:
  g:
    cmds:
      - |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        protos/hello.proto
  gen:
    desc: gen protos protos.go file
    cmds:
      - protoc --go_out=plugins=grpc:. protos/*.proto

  run:
    desc: start grpc server
    cmds:
      - go run -v server/cmd/main.go

  # buf.build
  buf-init:
    desc: init buf config
    cmds:
      - buf beta mod init
      - cat buf.yaml

  # buf commands
  # - buf breaking --against '.git#branch=master'
  # - buf breaking --against '.git#tag=v1.0.0'
  # docker version, entrypoint: buf
  # docker pull bufbuild/buf
  # docker run --volume "$(pwd):/workspace" --workdir "/workspace" bufbuild/buf lint

  try:
    desc: try it
    cmds:
      - |
        grpcurl -plaintext -proto hellopb/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
          {
          "name": "geek"
          }
        EOM
  error:
   desc: try with error
   cmds:
     - |
       grpcurl -plaintext -proto hellopb/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
         {
         "name": "geek",
         "error": "error"
         }
       EOM

  dd:
    desc: try request datadog
    cmds:
      - |
        for i in {1..1000}; do echo $i; grpcurl -plaintext -proto hello/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
          {
          "name": "geek"
          }
        EOM
        done

  dde:
    desc: try request datadog with error
    cmds:
      - |
        for i in {1..50}; do echo $i; grpcurl -plaintext -proto hello/hello.proto -d @ localhost:50051 hello.Greeter.SayHello <<-EOM | jq
        {
          "name": "geek",
          "error": "error"
        }
        EOM
        sleep 0.5
        done