# https://taskfile.dev
version: '2'

tasks:
  # hello world
  build:
    desc: build hello world
    cmds:
      - protoc -I . helloworld/helloworld.proto --go_out=plugins=grpc:.
  server:
    desc: run hello world server
    cmds:
      - go run greeter_server/main.go
  client:
    desc: run hello world client
    cmds:
      - go run greeter_client/main.go
