# https://taskfile.dev
version: '2'

tasks:
  # pb world
  build:
    desc: build pb world
    cmds:
      - protoc -I . helloworld/helloworld.proto --go_out=plugins=grpc:.
  server:
    desc: run pb world server
    cmds:
      - go run greeter_server/main.go
  client:
    desc: run pb world client
    cmds:
      - go run greeter_client/main.go
