# https://taskfile.dev
version: '2'

tasks:
  # protos world
  build:
    desc: build protos world
    cmds:
      - protoc -I . helloworld/helloworld.proto --go_out=plugins=grpc:.
  server:
    desc: run protos world server
    cmds:
      - go run greeter_server/main.go
  client:
    desc: run protos world client
    cmds:
      - go run greeter_client/main.go
