# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Main Actions
on:
  push:
    branches:
    - master
jobs:
  go:
    name: Golang
    runs-on: ubuntu-18.04
    steps:
    - name: Install Task
      uses: Arduino/actions/setup-taskfile@master
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Install golangci-lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.20.0
        sudo mv bin/golangci-lint /usr/local/bin
        golangci-lint --version
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Lint
      run: task lint

    # - name: Test
    #   run: task dk-test

    # todo: coverage

    # - name: Build
    #   run: go build -v cmd/main.go
    # - name: try run
    #   run: go run main.go -v
