name: CI

on: [push]
# todo limit branch or event

jobs:
  try:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: try actions env
      run: printenv | sort
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13' # The Go version to download (if necessary) and use.
    - run: go run main.go -v


# todo test if one step failed
# test docker-compose with db, es