name: CI

# on: [push, pull_request]
# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on
on:

  push:
    branches:
      - master
      - ci*
  pull_request:
    branches:
    - master

jobs:
  # try: # job id
  #   name: Try actions env
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - name: inspect env
  #     run: printenv | sort
  #   # - name: Run a one-line script
  #   #   run: echo Hello, world!
  #   # - name: Run a multi-line script
  #   #   run: |
  #   #     echo Add other actions to build,
  #   #     echo test, and deploy your project.

  ######################################################################
  #               Golang
  try-go:
    name: Try Golang
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: '1.13' # The Go version to download (if necessary) and use.
      id: go
    - name: Install task 
      # todo version
      run: |
        go get -u -v github.com/go-task/task/cmd/task
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 2
    # todo mock lint error
    - name: Lint Go Code
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        go get -u -v golang.org/x/lint/golint 
        task --version
        task lint

    # - name: Copy .netrc to home directory
    #   run: cp .netrc ~/
    # - name: Install golangci-lint
    #   run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.20.0
    # - name: Lint
    #   run: ./bin/golangci-lint run

    # - name: Build
    #   run: go build -v main.go

    # - run: ./main  

  ######################################################################
  #               Docker
  # try-docker:
  #   name: Try docker env
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - name: inspect env
  #     run: docker-compose
