name: CI

on: [push]
# todo limit branch or event

jobs:
  try: # job id
    name: try env
    runs-on: ubuntu-18.04
    steps:
    - name: inspect env
      run: printenv | sort
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.

  try-go:
    name: Try Golang
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: '1.13' # The Go version to download (if necessary) and use.
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 2

    # - name: Copy .netrc to home directory
    #   run: cp .netrc ~/

    # - name: Install golangci-lint
    #   run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.20.0

    # - name: Lint
    #   run: ./bin/golangci-lint run

    # - name: Build
    #   run: go build -v cmd/main.go

    - run: go run main.go -v